# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7eb1a1b2fd957bc2aca87ef614b9ce1c1340a736fd02ae2d11723b78377215032925ddff7214163037bf25105593a52731221b910f7f858e917f81c3e59f72ac

test:
  secret_key_base: 8426267c035011c40c5fd1a59f7b7bbf57f0186338bbd9af4a8d0e6ffdfe8ffd4d93ad46a6393f4fbcd19ef3ed51b30d12f8a6b2e35e9e92f780afc7e1d201c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
